import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layouts/main";
import ProviderWrapper from "@/providers/provider-wrapper";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className} bg-background text-foreground antialiased`}
      >
        <ProviderWrapper>
          <MainLayout>{children}</MainLayout>
        </ProviderWrapper>
      </body>
    </html>
  );
}
